### ISSUE TITLE
四月是你的谎言 繁中 EP19 字体错误

### ISSUE THREAD

**Issue by SeanPhy** [HaruhanaSub/Haruhana-Fansub_Source#2]
乐曲英文名错误使用了 2FMQD2JM 字体（如图），对照简中及前后 EP 应为 Reed Headline。
![Screenshot 2024-12-14 082055](https://github.com/user-attachments/assets/1344f008-be5e-4f1c-8f6a-582721bc6270)

**Comment by Needfire-Gl** [comment]
感谢报错，已修正
修正履历：
（2024-12-22）修正错字、错译（ep03，07，09，13，15，16，17，22）
（2024-12-22）修正时轴、样式（ep19）
